name: Update CSV Dataset Records from Taiwan CDC website

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Update COVD-19 Labs
        run: python Fetcher/LabFetcher.py
      - name: Update MOHW RSS News
        run: python Fetcher/MohwRssFetcher.py
      - name: Update COVID-19 global cases and deaths
        run: python Fetcher/GlobalCasesFetcher.py
      - name: Update COVID-19 TW datasets
        run: python Fetcher/DailyCovid19TW.py
      - name: Copy JSON files to assets folder
        run: cp datasets/*.json web/src/assets/
      - name: Commit and push if it changed
        run: |
          git config user.name "peter279k"
          git config user.email "peter279k@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last Commit: ${timestamp}(TW)" || exit 0
          git push origin master
