name: 'Web Build and Deploy'

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Download JSON files to assets folder
        run: |
          wget -O web/src/assets/DayConfirmationAgeCountyGender19CoV.json https://github.com/peter279k/covid19-tw-news/raw/master/datasets/DayConfirmationAgeCountyGender19CoV.json
          wget -O web/src/assets/covid19_data.json https://github.com/peter279k/covid19-tw-news/blob/master/datasets/covid19_data.json
          wget -O web/src/assets/covid19_global_cases_and_deaths.json https://github.com/peter279k/covid19-tw-news/raw/master/datasets/covid19_global_cases_and_deaths.json
          wget -O web/src/assets/covid19_labs.json https://github.com/peter279k/covid19-tw-news/raw/master/datasets/covid19_labs.json
          wget -O web/src/assets/mohw_rss.json https://github.com/peter279k/covid19-tw-news/raw/master/datasets/mohw_rss.json

      - name: Install and Build 🔧
        working-directory: web
        run: |
          cp .env.example .env
          export NODE_OPTIONS="--max-old-space-size=8192"
          export VUE_APP_MAPKEY=${{ secrets.VUE_APP_MAPKEY }}
          sed -i -e "s/MAP_KEY/$VUE_APP_MAPKEY/g" ./.env
          npm install
          npm run build
          cd dist
          cp index.html 404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GIT_CONFIG_NAME: "peter279k"
          GIT_CONFIG_EMAIL: "peter279k@gmail.com"
          SINGLE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: web//dist
