name: 'Web Build and Deploy'

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          lfs: true

      - name: Install and Build 🔧
        working-directory: web
        run: |
          cp .env.example .env
          export NODE_OPTIONS="--max-old-space-size=8192"
          export VUE_APP_MAPKEY=${{ secrets.VUE_APP_MAPKEY }}
          sed -i -e "s/MAP_KEY/$VUE_APP_MAPKEY/g" ./.env
          npm install
          npm run build
          cd dist
          cp index.html 404.html

      - name: Install the SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to remote server via rsync 🚀
        run: rsync -avz ./web/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/covid19-tw-news.peterli.website/dist
